### ISSUE TITLE
Should expectation decorators add expectations that cannot be executed to the expectation configuration?

### ISSUE THREAD

**Issue by jcampbell** [abegong/great_expectations#3]
For example, if an expectation is written on a column that does not exist, currently that expectation will immediately be added, even if it is never even evaluated.

**Comment by abegong** [comment]
POV: Not by default, but users should be able to change that behavior at the expectation or DataSet level.

**Comment by jcampbell** [comment]
I think this is related to #33 (and that if they should be able to choose to add such expectations that is actually another parameter for the enhanced decorators).

**Comment by abegong** [comment]
+1. Closing and redirecting to Issue #33 .
