### ISSUE TITLE
expect_column_proportion_of_unique_values_to_be_between doesn't work without optional field max_value

### ISSUE THREAD

**Issue by thethingstheycoded** [abegong/great_expectations#50]
Returns False:
'data_set.expect_column_proportion_of_unique_values_to_be_between(column="ID_COLUMN", min_value=1, include_config=True)['success']

Returns True:
'data_set.expect_column_proportion_of_unique_values_to_be_between(column="ID_COLUMN", min_value=1, max_value=1, include_config=True)['success']

**Comment by jcampbell** [comment]
Seems reasonable to have min_value and max_value both default to None, and to only apply the relevant checks in the case that they are set.

**Comment by jcampbell** [comment]
Thanks for catching this. We've got a fix in develop for the next release.
